# Generated by Django 5.1.4 on 2025-01-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_rg_id_alter_user_u_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(db_column='is_admin', default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(db_column='is_manager', default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(db_column='is_staff', default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(db_column='is_superuser', default=False),
        ),
    ]
