# Generated by Django 5.1.4 on 2025-01-15 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_admin_user_is_employee_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Users', 'verbose_name_plural': 'Users'},
        ),
    ]
