# Generated by Django 5.1.4 on 2025-01-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visible',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
