# Generated by Django 5.1.4 on 2025-01-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='visible',
            field=models.JSONField(default=list, null=True),
        ),
    ]
