# Generated by Django 5.0.11 on 2025-02-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='visible',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
