# Generated by Django 5.0.11 on 2025-02-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='U_Role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('SuperAdmin', 'SuperAdmin')], db_column='U_Role', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='U_sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], db_column='U_Sex', max_length=45, null=True),
        ),
    ]
