# Generated by Django 5.0.11 on 2025-02-06 04:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_u_role_alter_user_u_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='RG_ID',
            field=models.CharField(blank=True, db_column='RG_ID', max_length=45, null=True, verbose_name='RG_ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='U_ID',
            field=models.IntegerField(db_column='U_ID', null=True, verbose_name='User_ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='U_Role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('SuperAdmin', 'SuperAdmin')], db_column='U_Role', max_length=45, null=True, verbose_name='User Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='U_address',
            field=models.CharField(blank=True, db_column='U_Address', max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='U_fullname',
            field=models.CharField(blank=True, db_column='U_FullName', max_length=45, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='U_phone',
            field=models.CharField(blank=True, db_column='U_Phone', max_length=45, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='U_sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], db_column='U_Sex', max_length=45, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(db_column='date_joined', default=django.utils.timezone.now, verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(db_column='is_admin', default=False, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(db_column='is_manager', default=False, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(db_column='is_superuser', default=False, verbose_name='Super Admin'),
        ),
    ]
