# Generated by Django 5.0.11 on 2025-02-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_rg_id_alter_user_u_id_alter_user_u_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_employee',
        ),
        migrations.AddField(
            model_name='user',
            name='is_radiologist_user',
            field=models.BooleanField(db_column='is_radiologist', default=False, verbose_name='Radiologist'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_ref_physician_user',
            field=models.BooleanField(db_column='is_ref_physician', default=False, verbose_name='Referral Physician'),
        ),
        migrations.AlterField(
            model_name='user',
            name='U_Role',
            field=models.CharField(blank=True, choices=[('ReferralPhysician', 'Referral Physician'), ('Radiologist', 'Radiologist'), ('Admin', 'Admin'), ('SuperAdmin', 'Super Admin')], db_column='U_Role', max_length=45, null=True, verbose_name='User Role'),
        ),
    ]
