# Generated by Django 5.1.4 on 2025-01-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referralphysician',
            fields=[
                ('Ref_Inc_ID', models.BigAutoField(db_column='Ref_inc_id', editable=False, primary_key=True, serialize=False, unique=True)),
                ('Ref_ID', models.CharField(blank=True, db_column='Ref_ID', max_length=500, null=True)),
                ('Ref_Phy_Name', models.CharField(blank=True, db_column='Ref_phy_name', max_length=50, null=True)),
                ('Ref_Phy_Phone', models.CharField(blank=True, db_column='Ref_phy_phone', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
