# Generated by Django 5.1.4 on 2025-01-08 09:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referralphysician',
            fields=[
                ('physician_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ref_inc_id', models.PositiveBigIntegerField(db_column='Ref_inc_id', unique=True)),
                ('ref_id', models.CharField(blank=True, db_column='Ref_ID', max_length=500, null=True)),
                ('ref_phy_name', models.CharField(blank=True, db_column='Ref_phy_name', max_length=50, null=True)),
                ('ref_phy_phone', models.CharField(blank=True, db_column='Ref_phy_phone', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
