# Generated by Django 5.1.4 on 2025-01-15 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referralPhysician', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referralphysician',
            options={'verbose_name': 'Referral Physician', 'verbose_name_plural': 'Referral Physician'},
        ),
    ]
