# Generated by Django 5.1.4 on 2025-01-11 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studies',
            name='pat_inc_id_det',
        ),
        migrations.AddField(
            model_name='studies',
            name='pat_inc_id_del',
            field=models.ForeignKey(blank=True, db_column='Pat_Inc_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pat_inc_id_del', to='patients.patients'),
        ),
    ]
