# Generated by Django 5.1.4 on 2025-01-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studies',
            name='study_inc_id',
            field=models.AutoField(db_column='Study_inc_id', primary_key=True, serialize=False, unique=True),
        ),
    ]
