# Generated by Django 5.1.4 on 2025-01-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_remove_studies_pat_inc_id_det_studies_pat_inc_id_del'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studies',
            old_name='pat_inc_id_del',
            new_name='pat_inc_id_det',
        ),
    ]
