# Generated by Django 5.1.4 on 2025-01-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_rename_pat_inc_id_del_studies_pat_inc_id_det'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studies',
            options={'verbose_name': 'Studies', 'verbose_name_plural': 'Studies'},
        ),
        migrations.AlterField(
            model_name='studies',
            name='status_reported',
            field=models.CharField(blank=True, db_column='Status_Reported', max_length=25, null=True),
        ),
    ]
