# Generated by Django 5.1.4 on 2025-01-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('Pat_Inc_ID', models.BigAutoField(db_column='Pat_inc_id', editable=False, primary_key=True, serialize=False, unique=True)),
                ('Pat_Inc_ID_string', models.CharField(blank=True, db_column='Pat_inc_id_string', max_length=50, null=True)),
                ('Pat_ID', models.CharField(blank=True, db_column='Pat_id', max_length=50, null=True)),
                ('Pat_Name', models.CharField(blank=True, db_column='Pat_name', max_length=70, null=True)),
                ('Pat_Sex', models.CharField(blank=True, db_column='Pat_sex', max_length=10, null=True)),
                ('Pat_DOB', models.DateField(blank=True, db_column='Pat_DOB', null=True)),
                ('Pat_Phone', models.CharField(blank=True, db_column='Pat_phone', max_length=25, null=True)),
                ('Notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
