# Generated by Django 5.1.4 on 2025-01-15 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patients',
            options={'verbose_name': 'Patients', 'verbose_name_plural': 'Patients'},
        ),
    ]
