# Generated by Django 5.1.4 on 2025-01-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadiologyGroup',
            fields=[
                ('rg_inc_id', models.PositiveBigIntegerField(db_column='RG_Inc_ID', primary_key=True, serialize=False)),
                ('rg_id', models.IntegerField(blank=True, db_column='RG_ID', null=True)),
                ('rg_name', models.CharField(blank=True, db_column='RG_Name', max_length=45, null=True)),
                ('rg_members', models.CharField(blank=True, db_column='RG_Members', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
