# Generated by Django 5.1.4 on 2025-01-15 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiologyGroup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radiologygroup',
            options={'verbose_name': 'Radiology Group', 'verbose_name_plural': 'Radiology Group'},
        ),
    ]
